sudo: required
services:
  - docker

before_install:
  - docker build -t mwints/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mwints/react-test npm test -- --coverage

after_success:
  - docker build -t mwints/multi-client ./client
  - docker build -t mwints/multi-nginx ./nginx
  - docker build -t mwints/multi-server ./server
  - docker build -t mwints/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push mwints/multi-client
  - docker push mwints/multi-nginx
  - docker push mwints/multi-server
  - docker push mwints/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker-2
  env: MultiDocker2-env
  bucket_name: elasticbeanstalk-eu-central-1-980554874121
  bucket_path: multi-docker-2
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
